"""Initial migration.

Revision ID: 949506015b89
Revises: 
Create Date: 2024-06-27 09:13:28.487379

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '949506015b89'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interviews')
    op.drop_table('resumes')
    op.drop_table('resume')
    op.drop_table('reviews')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('last_name', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('user_type', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('id', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('reviews',
    sa.Column('user_id', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('resume_link', mysql.VARCHAR(length=1024), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('review', mysql.VARCHAR(length=1024), nullable=True),
    sa.Column('id', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='reviews_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('resume',
    sa.Column('user_id', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('resume_link', mysql.VARCHAR(length=1024), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('review', mysql.VARCHAR(length=1024), nullable=True),
    sa.Column('id', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='resume_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('resumes',
    sa.Column('user_id', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('resume_link', mysql.VARCHAR(length=1024), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('review', mysql.VARCHAR(length=1024), nullable=True),
    sa.Column('resume_type', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('id', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='resumes_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('interviews',
    sa.Column('user_id', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('resume_link', mysql.VARCHAR(length=1024), nullable=False),
    sa.Column('application_link', mysql.VARCHAR(length=1024), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('datails', mysql.VARCHAR(length=1024), nullable=True),
    sa.Column('id', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='interviews_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
